{{- if .Values.externalsecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "..fullname" . }}-postgresql-secret
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ include "..fullname" . }}-postgresql-secret
    template:
      metadata:
        labels: {}
  data:
  - secretKey: postgresql-password
    remoteRef:
      key: {{ .Values.externalsecrets.postgresqlKey }}
      property: postgresql-password
  - secretKey: postgresql-admin-password
    remoteRef:
      key: {{ .Values.externalsecrets.postgresqlKey }}
      property: postgresql-admin-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "..fullname" . }}-odoo-conf-secret
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ include "..fullname" . }}-odoo-conf
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels: {}
      data:
        odoo.conf: |
          [options]
          proxy_mode = {{ .Values.odoo.proxy_mode }}
          {{- if .Values.odoo.addons_path }}
          addons_path = {{ .Values.odoo.addons_path }}
          {{- end }}
          server_wide_modules = {{ .Values.odoo.server_wide_modules }}
          data_dir = /var/lib/odoo
          workers = {{ .Values.odoo.workers | int }}
          limit_memory_soft = {{ .Values.odoo.limit_memory_soft | int }}
          limit_memory_hard = {{ .Values.odoo.limit_memory_hard | int }}
          limit_time_cpu = {{ .Values.odoo.limit_time_cpu | int }}
          limit_time_real = {{ .Values.odoo.limit_time_real | int }}
          limit_time_real_cron = {{ .Values.odoo.limit_time_real_cron | int }}
          limit_request = {{ .Values.odoo.limit_request | int }}
          {{- if .Values.odoo.dbfilter }}
          dbfilter = {{ .Values.odoo.dbfilter }}
          {{- end }}
          db_host = {{ .Values.postgresql.host }}
          {{- if .Values.odoo.db_name }}
          db_name = {{ .Values.postgresql.auth.database }}
          {{- else }}
          db_name = False
          {{- end }}
          db_port = {{ .Values.postgresql.port }}
          db_user = {{ .Values.postgresql.auth.username }}
          db_password = {{ `{{ .postgresqlPassword }}` }}
          db_maxconn = {{ .Values.odoo.db_maxconn }}
          without_demo = {{ .Values.odoo.without_demo }}
          admin_passwd = {{ `{{ .odooAdminPasswd }}` }}
          list_db = {{ .Values.odoo.list_db }}
          smtp_server = {{ .Values.odoo.smtp_server }}
          load_language = {{ .Values.odoo.load_language }}
          log_level = {{ .Values.odoo.log_level }}
          log_handler = {{ .Values.odoo.log_handler }}
  data:
  - secretKey: postgresqlPassword
    remoteRef:
      key: {{ .Values.externalsecrets.odooKey }}
      property: postgresql-password
  - secretKey: odooAdminPasswd
    remoteRef:
      key: {{ .Values.externalsecrets.odooKey }}
      property: odoo-admin-passwd
{{- end }}
