{{- if .Values.externalsecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "..fullname" . }}-postgresql-secret
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ include "..fullname" . }}-postgresql-secret
    template:
      metadata:
        labels: {}
  data:
  - secretKey: postgresql-password
    remoteRef:
      key: {{ .Values.externalsecrets.postgresqlKey }}
      property: postgresql-password
  - secretKey: postgresql-admin-password
    remoteRef:
      key: {{ .Values.externalsecrets.postgresqlKey }}
      property: postgresql-admin-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "..fullname" . }}-odoo-conf-secret
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ include "..fullname" . }}-odoo-conf
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels: {}
      data:
        odoo.conf: |
{{ include "..odooConf" (dict "Values" .Values "dbPassword" "{{ .postgresqlPassword }}" "adminPasswd" "{{ .odooAdminPasswd }}") | indent 10 }}
  data:
  - secretKey: postgresqlPassword
    remoteRef:
      key: {{ .Values.externalsecrets.odooKey }}
      property: postgresql-password
  - secretKey: odooAdminPasswd
    remoteRef:
      key: {{ .Values.externalsecrets.odooKey }}
      property: odoo-admin-passwd
{{- end }}
