{{- if or (not .Values.existingSecret.enabled) (not .Values.externalsecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "..fullname" . }}-postgresql-secret"
  annotations:
    labels:
        {{- include "..labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.postgresql.auth.password }}
  postgresql-admin-password: {{ .Values.postgresql.auth.admin_password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "..fullname" . }}-odoo-conf"
  annotations:
    labels:
        {{- include "..labels" . | nindent 4 }}
type: Opaque
stringData:
  odoo.conf: |
    [options]
    proxy_mode = {{ .Values.odoo.proxy_mode }}
    {{- if .Values.odoo.addons_path }}
    addons_path = {{ .Values.odoo.addons_path }}
    {{- end }}
    server_wide_modules = {{ .Values.odoo.server_wide_modules }}
    data_dir = /var/lib/odoo
    workers = {{ .Values.odoo.workers | int }}
    limit_memory_soft = {{ .Values.odoo.limit_memory_soft | int }}
    limit_memory_hard = {{ .Values.odoo.limit_memory_hard | int }}
    limit_time_cpu = {{ .Values.odoo.limit_time_cpu | int }}
    limit_time_real = {{ .Values.odoo.limit_time_real | int }}
    limit_time_real_cron = {{ .Values.odoo.limit_time_real_cron | int }}
    limit_request = {{ .Values.odoo.limit_request | int }}
    {{- if .Values.odoo.dbfilter }}
    dbfilter = {{ .Values.odoo.dbfilter }}
    {{- end }}
    db_host = {{ .Values.postgresql.host }}
    {{- if .Values.odoo.db_name }}
    db_name = {{ .Values.postgresql.auth.database }}
    {{- else }}
    db_name = False
    {{- end }}
    db_port = {{ .Values.postgresql.port }}
    db_user = {{ .Values.postgresql.auth.username }}
    db_password = {{ .Values.postgresql.auth.password }}
    db_maxconn = {{ .Values.odoo.db_maxconn }}
    without_demo = {{ .Values.odoo.without_demo }}
    admin_passwd = {{ .Values.odoo.admin_passwd }}
    list_db = {{ .Values.odoo.list_db }}
    smtp_server = {{ .Values.odoo.smtp_server }}
    load_language = {{ .Values.odoo.load_language }}
    log_level = {{ .Values.odoo.log_level }}
    log_handler = {{ .Values.odoo.log_handler }}
{{- end }}
