---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-nginx
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: nginx-http
      port: {{ .Values.service.port }}
      targetPort: nginx-http
      protocol: TCP
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-odoo
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: odoo-http
      port: 8069
      targetPort: odoo-http
      protocol: TCP
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-lp-odoo
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: odoo-lp-http
      port: 8072
      targetPort: odoo-lp-http
      protocol: TCP
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
{{- if .Values.maintenance.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-maintenance-page
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
{{- end }}