---
name: Helm Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Helm Release
        uses: IMIO/gha/helm-release-notify@v8
        with:
          HELM_VERSION: '4.2.3'
          TARGET_DIR: odoo
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SIGNER_KEY: ${{ secrets.HELM_SIGNER_KEY }}
          SIGNER_KEY_ID: ${{ secrets.HELM_SIGNER_KEY_ID }}
          SIGNER_KEY_PASSPHRASE: ${{ secrets.HELM_SIGNER_KEY_PASSPHRASE }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
