---
name: Lint and Test Charts on PR
    
on: [pull_request]
    
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and Test Charts
        uses: IMIO/gha/helm-test-notify@v7
        with:
          HELM_RELEASE: odoo
          HELM_NAMESPACE: odoo
